server:
  port: 8090
spring:
  data:
    mongodb:
      host: ${EL_MONGO_HOST}
      port: ${EL_MONGO_PORT}
      database: ${EL_MONGO_DB}
      user: ${EL_MONGO_USER}
      password: ${EL_MONGO_PASSWD}

app:
  context-path: ${EL_CONTEXT_PATH}
  iam-client:
    organization-id: ${EL_ORGANIZATION_ID}
    project-id: ${EL_PROJECT_ID}
    base-url: ${EL_IAM_BASE_URL}
    polling-interval: 30
    time-unit: SECONDS

logging:
  level:
    root: INFO
    one:
      microproject:
        iamservice:
          client:
            impl: ${EL_LOGLEVEL:INFO}
