server:
  port: ${PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

app:
  elastic-host: ${ELASTIC_HOST}
  elastic-port: ${ELASTIC_PORT}
  elastic-user: ${ELASTIC_USER}
  elastic-pass: ${ELASTIC_PASS}