# event-logger infrastructure only stack

version: '3.7'

services:
  iamservice:
    image: jurajveverka/iam-service:2.5.9-RELEASE
    ports:
      - 8080:8080
  mongodb:
    image: mongo:4.2.12
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: loggerdb
      MONGO_INITDB_ROOT_USERNAME: loggeruser
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:
    driver: local
