# event-logger stack

version: '3.7'

services:

  iamservice:
    image: jurajveverka/iam-service:2.5.10-RELEASE
    ports:
      - 8080:8080
    environment:
      APP_CONFIG_PATH: "/application-cloud.yml"
      IAM_CONTEXT_PATH: "/auth"
      IAM_AUTH_CODE_CACHE_CLEANUP_INTERVAL: 10
      IAM_CACHE_CLEANUP_INTERVAL: 10
      IAM_CACHE_TIME_UNIT: "MINUTES"
      IAM_CACHE_TYPE: "redis"
      IAM_REDIS_HOST: "redis"
      IAM_REDIS_PORT: 6379
      IAM_ADMIN_ENABLE_CLIENT_CREDENTIALS: "true"
      IAM_PERSISTENCE_TYPE: "mongo-db"
      IAM_MONGO_PERSISTENCE_HOST: "mongodb-iam"
      IAM_MONGO_PERSISTENCE_PORT: 27017
      IAM_MONGO_PERSISTENCE_DATABASE: "admin"
      IAM_MONGO_PERSISTENCE_USERNAME: "admin"
      IAM_MONGO_PERSISTENCE_PASSWORD: "secret"
      IAM_ROOT_LOGLEVEL: "INFO"
      IAM_LOGLEVEL: "INFO"
      IAM_ADMIN_PASSWORD: "secret"
      IAM_ADMIN_CLIENT_SECRET: "secret"
      IAM_ADMIN_EMAIL: "admin@iam-service.com"
    depends_on:
      - "redis"
      - "mongodb-iam"

  eventlogger:
    image: jurajveverka/event-logger:1.0.0-SNAPSHOT
    ports:
      - 8090:8090
    environment:
      APP_CONFIG_PATH: "/opt/data/application-cloud.yml"
      EL_CONTEXT_PATH: "/eventlogger"
      EL_MONGO_HOST: "mongodb-data"
      EL_MONGO_PORT: 27017
      EL_MONGO_DB: "admin"
      EL_MONGO_USER: "admin"
      EL_MONGO_PASSWD: "secret"
      EL_IAM_BASE_URL: "http://iamservice:8080/auth"
      EL_ORGANIZATION_ID: "backend-services"
      EL_PROJECT_ID: "microprojects"
      EL_LOGLEVEL: "INFO"
    depends_on:
      - "redis"
      - "mongodb-iam"

  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379

  mongodb-iam:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    volumes:
      - mongodb_iam_volume:/data/db

  mongodb-data:
    image: mongo:4.4.4-bionic
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    volumes:
      - mongodb_data_volume:/data/db

volumes:
  mongodb_iam_volume:
    driver: local
  mongodb_data_volume:
    driver: local
