
metricbeat.modules:
  # Metrics collected from a Prometheus endpoint
  - module: prometheus
    enabled: true
    period: 20s
    metricsets: ["collector"]
    hosts: ["localhost:8090"]
    metrics_path: "${EL_CONTEXT_PATH}/actuator/prometheus"
  - module: system
    enabled: true
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - uptime          # System Uptime
    period: 20s
    processes: ['.*']

output.elasticsearch:
  hosts: ["${ES_HOSTS}"]
